services:
  - type: web
    name: services-booking-backend
    env: node
    branch: master
    repo: https://github.com/your-repo
    buildCommand: npm install --prefix . && npm install --prefix web && npm run build --prefix web
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://servicehub-web-pryn.onrender.com
      - key: PORT
        value: 3000
